<?php
/**
 * Omregistreringsavgift
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Omregistreringsavgift API
 *
 * Tjenesten leverer omregistreringsavgiften for kjøretøy spesifisert av kjennemerke og eventuelt omregistreringsdato.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * Omregistreringsavgift Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Omregistreringsavgift implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Omregistreringsavgift';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'omregistreringsavgift' => '\Swagger\Client\Model\BeloepSomHeltall',
'kjennemerke' => '\Swagger\Client\Model\Identifikator',
'dato_omregistreringsavgift' => '\Swagger\Client\Model\Dato'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'omregistreringsavgift' => null,
'kjennemerke' => null,
'dato_omregistreringsavgift' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'omregistreringsavgift' => 'omregistreringsavgift',
'kjennemerke' => 'kjennemerke',
'dato_omregistreringsavgift' => 'datoOmregistreringsavgift'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'omregistreringsavgift' => 'setOmregistreringsavgift',
'kjennemerke' => 'setKjennemerke',
'dato_omregistreringsavgift' => 'setDatoOmregistreringsavgift'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'omregistreringsavgift' => 'getOmregistreringsavgift',
'kjennemerke' => 'getKjennemerke',
'dato_omregistreringsavgift' => 'getDatoOmregistreringsavgift'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['omregistreringsavgift'] = isset($data['omregistreringsavgift']) ? $data['omregistreringsavgift'] : null;
        $this->container['kjennemerke'] = isset($data['kjennemerke']) ? $data['kjennemerke'] : null;
        $this->container['dato_omregistreringsavgift'] = isset($data['dato_omregistreringsavgift']) ? $data['dato_omregistreringsavgift'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets omregistreringsavgift
     *
     * @return \Swagger\Client\Model\BeloepSomHeltall
     */
    public function getOmregistreringsavgift()
    {
        return $this->container['omregistreringsavgift'];
    }

    /**
     * Sets omregistreringsavgift
     *
     * @param \Swagger\Client\Model\BeloepSomHeltall $omregistreringsavgift omregistreringsavgift
     *
     * @return $this
     */
    public function setOmregistreringsavgift($omregistreringsavgift)
    {
        $this->container['omregistreringsavgift'] = $omregistreringsavgift;

        return $this;
    }

    /**
     * Gets kjennemerke
     *
     * @return \Swagger\Client\Model\Identifikator
     */
    public function getKjennemerke()
    {
        return $this->container['kjennemerke'];
    }

    /**
     * Sets kjennemerke
     *
     * @param \Swagger\Client\Model\Identifikator $kjennemerke kjennemerke
     *
     * @return $this
     */
    public function setKjennemerke($kjennemerke)
    {
        $this->container['kjennemerke'] = $kjennemerke;

        return $this;
    }

    /**
     * Gets dato_omregistreringsavgift
     *
     * @return \Swagger\Client\Model\Dato
     */
    public function getDatoOmregistreringsavgift()
    {
        return $this->container['dato_omregistreringsavgift'];
    }

    /**
     * Sets dato_omregistreringsavgift
     *
     * @param \Swagger\Client\Model\Dato $dato_omregistreringsavgift dato_omregistreringsavgift
     *
     * @return $this
     */
    public function setDatoOmregistreringsavgift($dato_omregistreringsavgift)
    {
        $this->container['dato_omregistreringsavgift'] = $dato_omregistreringsavgift;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
